const categoryRouter=require("./categoriesRouter")
const authRouter=require("./authRouter")
const userRouter=require("./userRouter")
const serviceRouter=require("./serviceRouter")
const authMiddleware=require("../middlewares/AuthMiddleware")
const commentRouter=require("../routers/commentRouter")
const bookingRouter=require("../routers/bookingRouter")
const apRouter=require("../routers/aiRouter")
const notificationRouter=require("../routers/notificationRouter")
const stripeRouter=require("../routers/stripeRouter")
function Router(app){
    app.use("/category",categoryRouter)
    app.use("/auth",authRouter)
    app.use("/user",authMiddleware,userRouter)
    app.use("/service",authMiddleware,serviceRouter)
    app.use("/comment",authMiddleware,commentRouter)
    app.use("/booking",authMiddleware,bookingRouter)
    app.use("/chatGPT",apRouter)
    app.use("/notification",authMiddleware,notificationRouter)
    app.use("/stripe",stripeRouter)
}
module.exports=Router